version: "3.8"
services:

  apache:
    container_name: apache-service
    build: ./docker/apache-service
    volumes: 
      - ./src:/var/www/html
      - ./docker/apache/httpd/conf:/etc/httpd/conf
      - ./docker/apache/httpd/conf.d/user-list.conf:/etc/httpd/conf.d/user-list.conf
    ports:
      - "8000:80"

  php:
    container_name: php-service
    build:
      args:
        user: user-list
        uid: 1000
      context: .
      dockerfile: ./docker/php-service/Dockerfile
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - mysql-server

  mysql:
    container_name: mysql-service
    image: mysql:8.0
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - TZ=${DB_TZ}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql-service/my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  db-data:
